### ISSUE TITLE
RSS feed

### ISSUE THREAD

**Issue by doppioandante** [jmorag/blog#1]
Hello, would you mind adding a RSS feed to you blog?
Regards

**Comment by jmorag** [comment]
Just added an item to the menu pointing to [blog.josephmorag.com/posts/index.xml](). [blog.josephmorag.com/index.xml]() should also work. Which one should the menu item point to? I imagine the posts link since that's where content is but I'm not at all familiar with RSS.

**Comment by doppioandante** [comment]
Thanks, I think the way it works now is ok. For some reason my rss aggregator (miniflux) can't find the rss automatically from the base url, but that's a minor problem, giving it the rss url directly works.
